# This rule is not used by the project kube-changejob itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over triggers.changejob.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-changejob
    app.kubernetes.io/managed-by: kustomize
  name: changetriggeredjob-admin-role
rules:
- apiGroups:
  - triggers.changejob.io
  resources:
  - changetriggeredjobs
  verbs:
  - '*'
- apiGroups:
  - triggers.changejob.io
  resources:
  - changetriggeredjobs/status
  verbs:
  - get
