apiVersion: triggers.changejob.dev/v1alpha
kind: ChangeTriggeredJob
metadata:
  labels:
    app.kubernetes.io/name: kube-changejob
    app.kubernetes.io/managed-by: kustomize
  name: changetriggeredjob-sample
spec:
  # TODO(user): Add fields here
